# --------------------------------------------------------------------------
# Substitutions
#
# These are substitutions as used by the configuration packages from below.
# You can uncomment and update the ones that you want to modify.
# --------------------------------------------------------------------------

substitutions:
  name: thomas-room-door-tof
  friendly_name: thomas-room-door-ToF
  device_name: thomas-room-door-ToF

esphome:
  name: ${name}
  friendly_name: ${friendly_name}

  on_boot:
    # ...
    then:
      # - number.to_min: personsInRoom
      - lambda: !lambda |-
          id(template_text).publish_state("Init Sensors");
          id(enter_room).publish_state(false);
          id(leave_room).publish_state(false);

esp8266:
  board: d1_mini

# Enable logging
logger:
  level: DEBUG
  logs:
    vl53l0x: ERROR
    sensor: ERROR
    number: ERROR


# Enable Home Assistant API
api:
  encryption:
    key: !secret api_encryption_key

ota:
  password: !secret ota_password
  platform: esphome

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: ${device_name}_fallback
    password: !secret ap_password

captive_portal:

i2c:
  sda: D2
  scl: D1

number:
  - platform: template
    name: "Persons in Room"
    id: personsInRoom
    optimistic: true
    min_value: 0
    max_value: 100
    step: 1
    mode: box
    restore_value: true
    internal: false
    on_value: 
      then:
        lambda: |-
            id(template_text).publish_state("'Persons in Room' changed to: " + (to_string(int(id(personsInRoom).state))));


  - platform: template
    name: "Door Distance 01"
    id: door_distance_01
    min_value: 0
    max_value: 1.5
    step: .1
    unit_of_measurement: "m"
    optimistic: true
    device_class: "distance"
    restore_value: true
    internal: true
    # on_value: 
    #   then:
    #     lambda: |-
    #         id(template_text).publish_state("'Door Distance 01' changed to: " + (to_string(id(door_distance_01).state)));

  - platform: template
    name: "Door Distance 02"
    id: door_distance_02
    min_value: 0
    max_value: 1.5
    step: .1
    unit_of_measurement: "m"
    optimistic: true
    device_class: "distance"
    restore_value: true
    internal: true
    # on_value: 
    #   then:
    #     lambda: |-
    #         id(template_text).publish_state("'Door Distance 02' changed to: " + (to_string(id(door_distance_02).state)));

  - platform: template
    name: "Door Distance Offset"
    id: door_distance_offset
    min_value: -.9
    max_value: 0
    restore_value: true
    step: .1
    unit_of_measurement: "m"
    optimistic: true
    device_class: "distance"
    initial_value: -.4
    mode: box
    on_value: 
      then:
        lambda: |-
            id(template_text).publish_state("'Door Distance Offset' changed to: " + (to_string(id(door_distance_offset).state)));
            id(door_distance_01).publish_state(id(distance01).state + id(door_distance_offset).state);
            id(door_distance_02).publish_state(id(distance02).state + id(door_distance_offset).state);

sensor:
  - platform: vl53l0x
    name: "distance sensor 01"
    id: distance01
    address: 0x41
    enable_pin: D3
    # timeout: 10ms
    update_interval: 33ms
    unit_of_measurement: "m"
    device_class: "distance"
    internal: true
    filters:
    - skip_initial: 100
    - median:
        window_size: 7
        send_every: 4
        send_first_at: 4
    - lambda: |-
        if(x == NAN) {
          id(template_text).publish_state("'Distance Sensor 01 == NAN'; Resetting to 0");
          return 0.0;
        };
        return x;
    on_value: 
      then:
        lambda: |-
            if(id(door_distance_01).state == 0){
              id(door_distance_01).publish_state(id(distance01).state + id(door_distance_offset).state);
            };
            id(door_distance_01_calibration).publish_state(id(distance01).state);


  - platform: vl53l0x
    name: "distance sensor 02"
    id: distance02
    address: 0x42
    enable_pin: D5
    # timeout: 10ms
    update_interval: 33ms
    unit_of_measurement: "m"
    device_class: "distance"
    internal: true
    filters:
    - skip_initial: 100
    - median:
        window_size: 7
        send_every: 4
        send_first_at: 4
    - lambda: |-
        if (x == NAN) {
          id(template_text).publish_state("'Distance Sensor 02 == NAN'; Resetting to 0");
          return 0.0;
          }
          return x;
    on_value: 
      then:
        lambda: |-
            if(id(door_distance_02).state == 0){
              id(door_distance_02).publish_state(id(distance02).state + id(door_distance_offset).state);
            };
            id(door_distance_02_calibration).publish_state(id(distance02).state);


  - platform: template
    name: "Calibrated Door Distance 01"
    id: door_distance_01_calibration
    device_class: "distance"
    filters:
      # - skip_initial: 120
      - clamp:
          min_value: 0.5
          ignore_out_of_range: true
      - sliding_window_moving_average:
          window_size: 165
          send_every: 8
          send_first_at: 8
    lambda: |-
      return id(distance01).state;
    on_value: 
      then:
        - lambda: |-
            id(door_distance_01).publish_state(id(door_distance_01_calibration).state + id(door_distance_offset).state);


  - platform: template
    name: "Calibrated Door Distance 02"
    id: door_distance_02_calibration
    device_class: "distance"
    filters:
      # - skip_initial: 120
      - clamp:
          min_value: 0.6
          ignore_out_of_range: true
      - sliding_window_moving_average:
          window_size: 165
          send_every: 8
          send_first_at: 8
    lambda: |-
      return id(distance02).state;
    on_value: 
      then:
        - lambda: |-
            id(door_distance_02).publish_state(id(door_distance_02_calibration).state + id(door_distance_offset).state);

binary_sensor:
  - platform: template
    name: Motion Sensor 01
    id: motion_sensor01
    internal: true
    device_class: "motion"
    filters:
      - delayed_off: 500ms
    lambda: !lambda |-
      return id(distance01).state <= id(door_distance_01).state && !id(leave_room).state && !id(enter_room).state;
    on_press:
        then:
          # First Check state of motion Sensor 02 to determine the direction of the walk
          # If motion sensor 02 is off, we know the motion comes from inside the room.
          - if:
              condition:
                binary_sensor.is_off: motion_sensor02
              then:
                - lambda: !lambda |-
                    id(template_text).publish_state("Detected motion from the inside. Waiting for 'Motion Sensor 02'");
                - while:
                    condition:
                      binary_sensor.is_on: motion_sensor01
                    # We can now wait for the motion sensor 02 to become true
                    then:
                      - wait_until:
                          binary_sensor.is_on: motion_sensor02

                      # If motion sensor 02 becoming true, we wait for the motion sensor 02 to return false again & the trigger of motion sensor 01.
                      # After that we can publish the leave_room state to true
                      - lambda: !lambda |-
                          id(template_text).publish_state("Person walked from sensor 01 to sensor 02");
                      - wait_until:
                            and:
                              - binary_sensor.is_off: motion_sensor02
                              - lambda: !lambda |-
                                  return id(distance01).state > id(door_distance_01).state;
                      - lambda: !lambda |-
                          id(leave_room).publish_state(true);
                          id(motion_sensor01).publish_state(false);
                      # Can't use lambda here because it would ignore the timeout of the binary_sensor
                      - binary_sensor.template.publish:
                          id: leave_room
                          state: OFF
              # If motion sensor 02 is on, we know the motion comes from outside the room. We don't need to do here anything
              else:
                - text_sensor.template.publish:
                    id: template_text
                    state: "'Motion Sensor 02' is already on. No walk in detected."
                - lambda: !lambda |-
                    id(motion_sensor01).publish_state(false);

  - platform: template
    name: Motion Sensor 02
    id: motion_sensor02
    internal: true
    device_class: "motion"
    filters:
      - delayed_off: 500ms
    lambda: !lambda |-
      return id(distance02).state <= id(door_distance_02).state && !id(leave_room).state && !id(enter_room).state;
    on_press:
      then:
        # First Check state of motion Sensor 01 to determine the direction of the walk
        # If motion sensor 01 is off, we know the motion comes from outside the room.
        - if:
            condition:
              binary_sensor.is_off: motion_sensor01
            then:
              - text_sensor.template.publish:
                  id: template_text
                  state: "Detected motion from the outside. Waiting for 'Motion Sensor 01'"
              - while:
                  condition:
                    binary_sensor.is_on: motion_sensor02
                  then:
                  # We can now wait for the motion sensor 01 to become true
                    - wait_until:
                        binary_sensor.is_on: motion_sensor01

                    # If motion sensor 01 becoming true, we wait for the motion sensor 01 & the trigger of motion sensor 02 to return false again.
                    # After that we can publish the enter_room state to true
                    - text_sensor.template.publish: 
                        id: template_text
                        state: "Person walked from sensor 02 to sensor 01"
                    - wait_until:
                        condition:
                          and:
                            - binary_sensor.is_off: motion_sensor01
                            - lambda: !lambda |-
                                return id(distance02).state > id(door_distance_02).state;
                    - lambda: !lambda |-
                        id(enter_room).publish_state(true);
                        id(motion_sensor02).publish_state(false);
                    # Can't use lambda here because it would ignore the timeout of the binary_sensor
                    - binary_sensor.template.publish:
                        id: enter_room
                        state: OFF
            # If motion sensor 01 is on, we know the motion comes from inside the room. We don't need to do here anything
            else:
              - text_sensor.template.publish:
                  id: template_text
                  state: "'Motion Sensor 01' is already on. No walk out detected."
              - lambda: !lambda |-
                  id(motion_sensor02).publish_state(false);

  - platform: template
    name: Enter Room
    id: enter_room
    internal: true
    device_class: "motion"
    on_press:
      then:
        - number.increment:
            id: personsInRoom
            cycle: false
        - lambda: |-
            id(template_text).publish_state("'enter_room' is true. Increment number.");

    filters:
      - delayed_off: 100ms

  - platform: template
    name: Leave Room
    id: leave_room
    device_class: "motion"
    internal: true
    on_press:
      then:
        - number.decrement:
            id: personsInRoom
            cycle: false
        - lambda: |-
            id(template_text).publish_state("'leave_room' is true. Decrement number.");
    filters:
      - delayed_off: 100ms

  - platform: template
    name: "Occupancy"
    id: occupancy
    lambda: |-
      return id(personsInRoom).state > 0;
    device_class: "occupancy"

# Logger for HA frontend
text_sensor:
  - platform: template
    id: template_text
    name: "Logger"

